stages:
  - build
  - test

compile:
  stage: build
  script:
    - qmake -qt=qt5 test_sql_queries.pro
    - make

test_sql_queries:
  stage: test
  script:
    - cd test
    - qmake -qt=qt5
    - make
    - ./test_sql_queries
